/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2024-01-23 05:23:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hospital.light;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class doctor_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Add Doctor</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("    <meta name=\"description\" content=\"Lucid Bootstrap 4.1.1 Admin Template\">\r\n");
      out.write("    <meta name=\"author\" content=\"WrapTheme, design by: ThemeMakker.com\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <!-- VENDOR CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/vendor/chartist/css/chartist.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/vendor/toastr/toastr.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- MAIN CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/color_skins.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"theme-cyan\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Loader -->\r\n");
      out.write("    <div class=\"page-loader-wrapper\">\r\n");
      out.write("        <div class=\"loader\">\r\n");
      out.write("            <div class=\"m-t-30\"><img src=\"../assets/images/logo-icon.svg\" width=\"48\" height=\"48\" alt=\"Lucid\"></div>\r\n");
      out.write("            <p>Please wait...</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Overlay For Sidebars -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-fixed-top\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"navbar-btn\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn-toggle-offcanvas\"><i class=\"lnr lnr-menu fa fa-bars\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-brand\">\r\n");
      out.write("                    <a href=\"index.html\"><img src=\"../assets/images/logo.svg\" alt=\"Lucid Logo\" class=\"img-responsive logo\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-right\">\r\n");
      out.write("                    <form id=\"navbar-search\" class=\"navbar-form search-form\">\r\n");
      out.write("                        <input value=\"\" class=\"form-control\" placeholder=\"Search here...\" type=\"text\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\"><i class=\"icon-magnifier\"></i></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"navbar-menu\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"doctor-events.html\" class=\"icon-menu d-none d-sm-block d-md-none d-lg-block\"><i class=\"icon-calendar\"></i></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"app-chat.html\" class=\"icon-menu d-none d-sm-block\"><i class=\"icon-bubbles\"></i></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"app-inbox.html\" class=\"icon-menu d-none d-sm-block\"><i class=\"icon-envelope\"></i><span class=\"notification-dot\"></span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"dropdown\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\" class=\"dropdown-toggle icon-menu\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"icon-bell\"></i>\r\n");
      out.write("                                <span class=\"notification-dot\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu notifications\">\r\n");
      out.write("                                    <li class=\"header\"><strong>You have 4 new Notifications</strong></li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                                            <div class=\"media\">\r\n");
      out.write("                                                <div class=\"media-left\">\r\n");
      out.write("                                                    <i class=\"icon-info text-warning\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"media-body\">\r\n");
      out.write("                                                    <p class=\"text\">Campaign <strong>Holiday Sale</strong> is nearly reach budget limit.</p>\r\n");
      out.write("                                                    <span class=\"timestamp\">10:00 AM Today</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                                            <div class=\"media\">\r\n");
      out.write("                                                <div class=\"media-left\">\r\n");
      out.write("                                                    <i class=\"icon-like text-success\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"media-body\">\r\n");
      out.write("                                                    <p class=\"text\">Your New Campaign <strong>Holiday Sale</strong> is approved.</p>\r\n");
      out.write("                                                    <span class=\"timestamp\">11:30 AM Today</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                                            <div class=\"media\">\r\n");
      out.write("                                                <div class=\"media-left\">\r\n");
      out.write("                                                    <i class=\"icon-pie-chart text-info\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"media-body\">\r\n");
      out.write("                                                    <p class=\"text\">Website visits from Twitter is 27% higher than last week.</p>\r\n");
      out.write("                                                    <span class=\"timestamp\">04:00 PM Today</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\">\r\n");
      out.write("                                            <div class=\"media\">\r\n");
      out.write("                                                <div class=\"media-left\">\r\n");
      out.write("                                                    <i class=\"icon-info text-danger\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"media-body\">\r\n");
      out.write("                                                    <p class=\"text\">Error on website analytics configurations</p>\r\n");
      out.write("                                                    <span class=\"timestamp\">Yesterday</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"footer\"><a href=\"javascript:void(0);\" class=\"more\">See all notifications</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"dropdown\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\" class=\"dropdown-toggle icon-menu\" data-toggle=\"dropdown\"><i class=\"icon-equalizer\"></i></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu user-menu menu-icon\">\r\n");
      out.write("                                    <li class=\"menu-heading\">ACCOUNT SETTINGS</li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-note\"></i> <span>Basic</span></a></li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-equalizer\"></i> <span>Preferences</span></a></li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-lock\"></i> <span>Privacy</span></a></li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-bell\"></i> <span>Notifications</span></a></li>\r\n");
      out.write("                                    <li class=\"menu-heading\">BILLING</li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-credit-card\"></i> <span>Payments</span></a></li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-printer\"></i> <span>Invoices</span></a></li>\r\n");
      out.write("                                    <li><a href=\"javascript:void(0);\"><i class=\"icon-refresh\"></i> <span>Renewals</span></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"page-login.html\" class=\"icon-menu\"><i class=\"icon-login\"></i></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"left-sidebar\" class=\"sidebar\">\r\n");
      out.write("            <div class=\"sidebar-scroll\">\r\n");
      out.write("                <div class=\"user-account\">\r\n");
      out.write("                    <img src=\"../assets/images/user.png\" class=\"rounded-circle user-photo\" alt=\"User Profile Picture\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <span>Welcome,</span>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"dropdown-toggle user-name\" data-toggle=\"dropdown\"><strong>Dr. Chandler Bing</strong></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu dropdown-menu-right account\">\r\n");
      out.write("                            <li><a href=\"doctor-profile.html\"><i class=\"icon-user\"></i>My Profile</a></li>\r\n");
      out.write("                            <li><a href=\"app-inbox.html\"><i class=\"icon-envelope-open\"></i>Messages</a></li>\r\n");
      out.write("                            <li><a href=\"javascript:void(0);\"><i class=\"icon-settings\"></i>Settings</a></li>\r\n");
      out.write("                            <li class=\"divider\"></li>\r\n");
      out.write("                            <li><a href=\"page-login.html\"><i class=\"icon-power\"></i>Logout</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <ul class=\"row list-unstyled\">\r\n");
      out.write("                        <li class=\"col-4\">\r\n");
      out.write("                            <small>Exp</small>\r\n");
      out.write("                            <h6>14</h6>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"col-4\">\r\n");
      out.write("                            <small>Awards</small>\r\n");
      out.write("                            <h6>13</h6>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"col-4\">\r\n");
      out.write("                            <small>Clients</small>\r\n");
      out.write("                            <h6>213</h6>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Nav tabs -->\r\n");
      out.write("                <ul class=\"nav nav-tabs\">\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link active\" data-toggle=\"tab\" href=\"#menu\">Menu</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"tab\" href=\"#sub_menu\"><i class=\"icon-grid\"></i></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"tab\" href=\"#Chat\"><i class=\"icon-book-open\"></i></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"tab\" href=\"#setting\"><i class=\"icon-settings\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tab panes -->\r\n");
      out.write("                <div class=\"tab-content p-l-0 p-r-0\">\r\n");
      out.write("                    <div class=\"tab-pane active\" id=\"menu\">\r\n");
      out.write("                        <nav class=\"sidebar-nav\">\r\n");
      out.write("                            <ul class=\"main-menu metismenu\">\r\n");
      out.write("                                <li class=\"active\"><a href=\"index.html\"><i class=\"icon-home\"></i><span>Dashboard</span></a></li>\r\n");
      out.write("                                <li><a href=\"app-appointment.html\"><i class=\"icon-calendar\"></i>Appointment</a></li>\r\n");
      out.write("                                <li><a href=\"app-taskboard.html\"><i class=\"icon-list\"></i>Taskboard</a></li>\r\n");
      out.write("                                <li><a href=\"app-inbox.html\"><i class=\"icon-home\"></i>Inbox App</a></li>\r\n");
      out.write("                                <li><a href=\"app-chat.html\"><i class=\"icon-bubbles\"></i>Chat App</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0);\" class=\"has-arrow\"><i class=\"icon-user-follow\"></i><span>Doctors</span> </a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"doctor-all.jsp\">All Doctors</a></li>\r\n");
      out.write("                                        <li><a href=\"doctor-add.html\">Add Doctor</a></li>\r\n");
      out.write("                                        <li><a href=\"doctor-profile.html\">Doctor Profile</a></li>\r\n");
      out.write("                                        <li><a href=\"doctor-events.html\">Doctor Schedule</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0);\" class=\"has-arrow\"><i class=\"icon-user\"></i><span>Patients</span> </a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"patients-all.html\">All Patients</a></li>\r\n");
      out.write("                                        <li><a href=\"patient-add.html\">Add Patient</a></li>\r\n");
      out.write("                                        <li><a href=\"patient-profile.html\">Patient Profile</a></li>\r\n");
      out.write("                                        <li><a href=\"patient-invoice.html\">Invoice</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0);\" class=\"has-arrow\"><i class=\"icon-wallet\"></i><span>Payments</span> </a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"payments.html\">Payments</a></li>\r\n");
      out.write("                                        <li><a href=\"payments-add.html\">Add Payment</a></li>\r\n");
      out.write("                                        <li><a href=\"payments-invoice.html\">Invoice</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0);\" class=\"has-arrow\"><i class=\"icon-layers\"></i><span>Departments</span> </a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"depa-add.html\">Add</a></li>\r\n");
      out.write("                                        <li><a href=\"depa-all.html\">All Departments</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Cardiology</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Pulmonology</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Gynecology</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Neurology</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Urology</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Gastrology</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Pediatrician</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void(0);\">Laboratory</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"our-centres.html\"><i class=\"icon-pointer\"></i>WorldWide Centres</a></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#Authentication\" class=\"has-arrow\"><i class=\"icon-lock\"></i><span>Authentication</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"page-login.html\">Login</a></li>\r\n");
      out.write("                                        <li><a href=\"page-register.html\">Register</a></li>\r\n");
      out.write("                                        <li><a href=\"page-lockscreen.html\">Lockscreen</a></li>\r\n");
      out.write("                                        <li><a href=\"page-forgot-password.html\">Forgot Password</a></li>\r\n");
      out.write("                                        <li><a href=\"page-404.html\">Page 404</a></li>\r\n");
      out.write("                                        <li><a href=\"page-403.html\">Page 403</a></li>\r\n");
      out.write("                                        <li><a href=\"page-500.html\">Page 500</a></li>\r\n");
      out.write("                                        <li><a href=\"page-503.html\">Page 503</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#Widgets\" class=\"has-arrow\"><i class=\"icon-puzzle\"></i><span>Widgets</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"widgets-statistics.html\">Statistics Widgets</a></li>\r\n");
      out.write("                                        <li><a href=\"widgets-data.html\">Data Widgets</a></li>\r\n");
      out.write("                                        <li><a href=\"widgets-chart.html\">Chart Widgets</a></li>\r\n");
      out.write("                                        <li><a href=\"widgets-weather.html\">Weather Widgets</a></li>\r\n");
      out.write("                                        <li><a href=\"widgets-social.html\">Social Widgets</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#Pages\" class=\"has-arrow\"><i class=\"icon-docs\"></i><span>Extra Pages</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"page-blank.html\">Blank Page</a> </li>\r\n");
      out.write("                                        <li><a href=\"doctor-profile.html\">Profile</a></li>\r\n");
      out.write("                                        <li><a href=\"page-gallery.html\">Image Gallery <span class=\"badge badge-default float-right\">v1</span></a> </li>\r\n");
      out.write("                                        <li><a href=\"page-gallery2.html\">Image Gallery <span class=\"badge badge-warning float-right\">v2</span></a> </li>\r\n");
      out.write("                                        <li><a href=\"page-timeline.html\">Timeline</a></li>\r\n");
      out.write("                                        <li><a href=\"page-timeline-h.html\">Horizontal Timeline</a></li>\r\n");
      out.write("                                        <li><a href=\"page-pricing.html\">Pricing</a></li>\r\n");
      out.write("                                        <li><a href=\"page-search-results.html\">Search Results</a></li>\r\n");
      out.write("                                        <li><a href=\"page-helper-class.html\">Helper Classes</a></li>\r\n");
      out.write("                                        <li><a href=\"page-maintenance.html\">Maintenance</a></li>\r\n");
      out.write("                                        <li><a href=\"page-testimonials.html\">Testimonials</a></li>\r\n");
      out.write("                                        <li><a href=\"page-faq.html\">FAQs</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-pane\" id=\"sub_menu\">\r\n");
      out.write("                        <nav class=\"sidebar-nav\">\r\n");
      out.write("                            <ul class=\"main-menu metismenu\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#uiElements\" class=\"has-arrow\"><i class=\"icon-diamond\"></i> <span>UI Elements</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"ui-typography.html\">Typography</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-tabs.html\">Tabs</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-buttons.html\">Buttons</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-bootstrap.html\">Bootstrap UI</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-icons.html\">Icons</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-notifications.html\">Notifications</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-colors.html\">Colors</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-dialogs.html\">Dialogs</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-list-group.html\">List Group</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-media-object.html\">Media Object</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-modals.html\">Modals</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-nestable.html\">Nestable</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-progressbars.html\">Progress Bars</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-range-sliders.html\">Range Sliders</a></li>\r\n");
      out.write("                                        <li><a href=\"ui-treeview.html\">Treeview</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#forms\" class=\"has-arrow\"><i class=\"icon-pencil\"></i> <span>Forms</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"forms-validation.html\">Form Validation</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-advanced.html\">Advanced Elements</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-basic.html\">Basic Elements</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-wizard.html\">Form Wizard</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-dragdropupload.html\">Drag &amp; Drop Upload</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-cropping.html\">Image Cropping</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-summernote.html\">Summernote</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-editors.html\">CKEditor</a></li>\r\n");
      out.write("                                        <li><a href=\"forms-markdown.html\">Markdown</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#Tables\" class=\"has-arrow\"><i class=\"icon-tag\"></i> <span>Tables</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"table-basic.html\">Tables Example<span class=\"badge badge-info float-right\">New</span></a> </li>\r\n");
      out.write("                                        <li><a href=\"table-normal.html\">Normal Tables</a> </li>\r\n");
      out.write("                                        <li><a href=\"table-jquery-datatable.html\">Jquery Datatables</a> </li>\r\n");
      out.write("                                        <li><a href=\"table-editable.html\">Editable Tables</a> </li>\r\n");
      out.write("                                        <li><a href=\"table-color.html\">Tables Color</a> </li>\r\n");
      out.write("                                        <li><a href=\"table-filter.html\">Table Filter <span class=\"badge badge-info float-right\">New</span></a> </li>\r\n");
      out.write("                                        <li><a href=\"table-dragger.html\">Table dragger <span class=\"badge badge-info float-right\">New</span></a> </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#charts\" class=\"has-arrow\"><i class=\"icon-bar-chart\"></i> <span>Charts</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"chart-e.html\">E Charts</a> </li>\r\n");
      out.write("                                        <li><a href=\"chart-morris.html\">Morris</a> </li>\r\n");
      out.write("                                        <li><a href=\"chart-flot.html\">Flot</a> </li>\r\n");
      out.write("                                        <li><a href=\"chart-chartjs.html\">ChartJS</a> </li>\r\n");
      out.write("                                        <li><a href=\"chart-jquery-knob.html\">Jquery Knob</a> </li>\r\n");
      out.write("                                        <li><a href=\"chart-sparkline.html\">Sparkline Chart</a></li>\r\n");
      out.write("                                        <li><a href=\"chart-peity.html\">Peity</a></li>\r\n");
      out.write("                                        <li><a href=\"chart-c3.html\">C3 Charts</a></li>\r\n");
      out.write("                                        <li><a href=\"chart-gauges.html\">Gauges</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#Maps\" class=\"has-arrow\"><i class=\"icon-map\"></i> <span>Maps</span></a>\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"map-google.html\">Google Map</a></li>\r\n");
      out.write("                                        <li><a href=\"map-yandex.html\">Yandex Map</a></li>\r\n");
      out.write("                                        <li><a href=\"map-jvectormap.html\">jVector Map</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-pane p-l-15 p-r-15\" id=\"Chat\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"input-group m-b-20\">\r\n");
      out.write("                                <div class=\"input-group-prepend\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"icon-magnifier\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <ul class=\"right_chat list-unstyled\">\r\n");
      out.write("                            <li class=\"online\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img class=\"media-object \" src=\"../assets/images/xs/avatar4.jpg\" alt=\"\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"name\">Dr. Chris Fox</span>\r\n");
      out.write("                                            <span class=\"message\">Dentist</span>\r\n");
      out.write("                                            <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"online\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img class=\"media-object \" src=\"../assets/images/xs/avatar5.jpg\" alt=\"\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"name\">Dr. Joge Lucky</span>\r\n");
      out.write("                                            <span class=\"message\">Gynecologist</span>\r\n");
      out.write("                                            <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"offline\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img class=\"media-object \" src=\"../assets/images/xs/avatar2.jpg\" alt=\"\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"name\">Dr. Isabella</span>\r\n");
      out.write("                                            <span class=\"message\">CEO, WrapTheme</span>\r\n");
      out.write("                                            <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"offline\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img class=\"media-object \" src=\"../assets/images/xs/avatar1.jpg\" alt=\"\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"name\">Dr. Folisise Chosielie</span>\r\n");
      out.write("                                            <span class=\"message\">Physical Therapy</span>\r\n");
      out.write("                                            <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"online\">\r\n");
      out.write("                                <a href=\"javascript:void(0);\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img class=\"media-object \" src=\"../assets/images/xs/avatar3.jpg\" alt=\"\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"name\">Dr. Alexander</span>\r\n");
      out.write("                                            <span class=\"message\">Audiology</span>\r\n");
      out.write("                                            <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-pane p-l-15 p-r-15\" id=\"setting\">\r\n");
      out.write("                        <h6>Choose Skin</h6>\r\n");
      out.write("                        <ul class=\"choose-skin list-unstyled\">\r\n");
      out.write("                            <li data-theme=\"purple\">\r\n");
      out.write("                                <div class=\"purple\"></div>\r\n");
      out.write("                                <span>Purple</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li data-theme=\"blue\">\r\n");
      out.write("                                <div class=\"blue\"></div>\r\n");
      out.write("                                <span>Blue</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li data-theme=\"cyan\" class=\"active\">\r\n");
      out.write("                                <div class=\"cyan\"></div>\r\n");
      out.write("                                <span>Cyan</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li data-theme=\"green\">\r\n");
      out.write("                                <div class=\"green\"></div>\r\n");
      out.write("                                <span>Green</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li data-theme=\"orange\">\r\n");
      out.write("                                <div class=\"orange\"></div>\r\n");
      out.write("                                <span>Orange</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li data-theme=\"blush\">\r\n");
      out.write("                                <div class=\"blush\"></div>\r\n");
      out.write("                                <span>Blush</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <h6>General Settings</h6>\r\n");
      out.write("                        <ul class=\"setting-list list-unstyled\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <label class=\"fancy-checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"checkbox\">\r\n");
      out.write("                                <span>Report Panel Usag</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <label class=\"fancy-checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"checkbox\">\r\n");
      out.write("                                <span>Email Redirect</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <label class=\"fancy-checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"checkbox\" checked>\r\n");
      out.write("                                <span>Notifications</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <label class=\"fancy-checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"checkbox\" checked>\r\n");
      out.write("                                <span>Auto Updates</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <label class=\"fancy-checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"checkbox\">\r\n");
      out.write("                                <span>Offline</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <label class=\"fancy-checkbox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"checkbox\" checked>\r\n");
      out.write("                                <span>Location Permission</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"main-content\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"block-header\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-8 col-sm-12\">\r\n");
      out.write("                            <h2><a href=\"javascript:void(0);\" class=\"btn btn-xs btn-link btn-toggle-fullwidth\"><i class=\"fa fa-arrow-left\"></i></a> Add Doctors</h2>\r\n");
      out.write("                            <ul class=\"breadcrumb\">\r\n");
      out.write("                                <li class=\"breadcrumb-item\"><a href=\"index.html\"><i class=\"icon-home\"></i></a></li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\">Doctor &nbsp; /&nbsp; Add Doctors</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-4 col-sm-12 text-right\">\r\n");
      out.write("                            <div class=\"bh_chart hidden-xs\">\r\n");
      out.write("                                <div class=\"float-left m-r-15\">\r\n");
      out.write("                                    <small>Visitors</small>\r\n");
      out.write("                                    <h6 class=\"mb-0 mt-1\"><i class=\"icon-user\"></i> 1,784</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"bh_visitors float-right\">2,5,1,8,3,6,7,5</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bh_chart hidden-sm\">\r\n");
      out.write("                                <div class=\"float-left m-r-15\">\r\n");
      out.write("                                    <small>Visits</small>\r\n");
      out.write("                                    <h6 class=\"mb-0 mt-1\"><i class=\"icon-globe\"></i> 325</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"bh_visits float-right\">10,8,9,3,5,8,5</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bh_chart hidden-sm\">\r\n");
      out.write("                                <div class=\"float-left m-r-15\">\r\n");
      out.write("                                    <small>Chats</small>\r\n");
      out.write("                                    <h6 class=\"mb-0 mt-1\"><i class=\"icon-bubbles\"></i> 13</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"bh_chats float-right\">1,8,5,6,2,4,3,2</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Form filling starting  -->\r\n");
      out.write("              	<div class=\"row clearfix\">\r\n");
      out.write("              		<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("              			<div class=\"card\">\r\n");
      out.write("              				<div class=\"header\">\r\n");
      out.write("              					<h2>Basic <span>Information</span>\r\n");
      out.write("              						<small>Full fillig from...</small>\r\n");
      out.write("              					</h2>\r\n");
      out.write("              				</div>\r\n");
      out.write("              				<div class=\"body\">\r\n");
      out.write("              					<form action=\"/hospital/src/main/java/backend/DoctorAdd\" method=\"Post\">\r\n");
      out.write("              					<div class=\"row clearfix\">\r\n");
      out.write("	              						<div class=\"col-lg-6 col-md-6 col-sm-12\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<input type=\"text\" class=\"form-control\" placeholder=\"First Name\" name=\"firstName\">\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              						<div class=\"col-lg-6 col-md-6 col-sm-12\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<input type=\"text\" class=\"form-control\" placeholder=\"Last Name\" name=\"lastName\">\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("              						</div>\r\n");
      out.write("              						<div class=\"row clearfix mt-3\">\r\n");
      out.write("              							<div class=\"col-sm-3\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<input type=\"text\" data-provid=\"datepicker\" data-date-autoclose=\"true\" class=\"form-control\" placeholder=\"Date Of Birth\" name=\"dob\">\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              							<div class=\"col-sm-3\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<select class=\"form-control\" name=\"gender\">\r\n");
      out.write("              										<option value>-Gender-</option>\r\n");
      out.write("              										<option value=\"10\">Male</option>\r\n");
      out.write("              										<option value=\"12\">Female</option>\r\n");
      out.write("              										<option value=\"14\">Other</option>\r\n");
      out.write("              									</select>\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              							<div class=\"col-sm-3\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<input type=\"text\" class=\"form-control\" placeholder=\"specialist\" name=\"specialist\">\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              							<div class=\"col-sm-3\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<input type=\"number\" class=\"form-control\" placeholder=\"Phone\" name=\"phone\">\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              						</div>\r\n");
      out.write("              						<div class=\"row clearfix\">\r\n");
      out.write("              							<div class=\"col-sm-6\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<input type=\"email\" class=\"form-control\" placeholder=\"Enter Your Email\" name=\"email\">\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              							<div class=\"col-sm-6\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<input type=\"text\" class=\"form-control\" placeholder=\"Website Url\" name=\"webSiteUrl\">\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              						</div>\r\n");
      out.write("              						<div class=\"row clearfix\">\r\n");
      out.write("              							<div class=\"col-12\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<input type=\"file\" class=\"dropify\">\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              						</div>\r\n");
      out.write("              						<div class=\"row clearfix\">\r\n");
      out.write("              							<div class=\"col-12\">\r\n");
      out.write("              								<div class=\"form-group\">\r\n");
      out.write("              									<textarea class=\"form-control\" rows=\"5\" cols=\"123\" placeholder=\"Please enter what you want..\" name=\"aboutDoctor\">        									\r\n");
      out.write("              									</textarea>\r\n");
      out.write("              								</div>\r\n");
      out.write("              							</div>\r\n");
      out.write("              						</div>\r\n");
      out.write("              	<div class=\"row clearfix\">\r\n");
      out.write("              		<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("              			<div class=\"card\">\r\n");
      out.write("              				<div class=\"header\">\r\n");
      out.write("              					<h2>Social <span>Media</span>\r\n");
      out.write("              						<small>Full filling URL...</small>\r\n");
      out.write("              					</h2>\r\n");
      out.write("              				</div>\r\n");
      out.write("              				<div class=\"body\">\r\n");
      out.write("              					<div class=\"row clearfix\">\r\n");
      out.write("	              						<div class=\"col-lg-6 col-md-6 col-sm-12\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<div class=\"input-group mb-3\">\r\n");
      out.write("												  <span class=\"input-group-text\" id=\"basic-addon1\">@</span>\r\n");
      out.write("												  <input type=\"text\" class=\"form-control\" placeholder=\"LinkedIn\" aria-label=\"Username\" aria-describedby=\"basic-addon1\" name=\"linkedIn\">\r\n");
      out.write("												</div>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              						<div class=\"col-lg-6 col-md-6 col-sm-12\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<div class=\"input-group mb-3\">\r\n");
      out.write("												  <span class=\"input-group-text\" id=\"basic-addon1\">@</span>\r\n");
      out.write("												  <input type=\"text\" class=\"form-control\" placeholder=\"Facebook\" aria-label=\"Username\" aria-describedby=\"basic-addon1\" name=\"facebook\">\r\n");
      out.write("												</div>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              						<div class=\"col-lg-6 col-md-6 col-sm-12\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<div class=\"input-group mb-3\">\r\n");
      out.write("												  <span class=\"input-group-text\" id=\"basic-addon1\">@</span>\r\n");
      out.write("												  <input type=\"text\" class=\"form-control\" placeholder=\"Twitter\" aria-label=\"Username\" aria-describedby=\"basic-addon1\" name=\"twitter\">\r\n");
      out.write("												</div>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              						<div class=\"col-lg-6 col-md-6 col-sm-12\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<div class=\"input-group mb-3\">\r\n");
      out.write("												  <span class=\"input-group-text\" id=\"basic-addon1\">@</span>\r\n");
      out.write("												  <input type=\"text\" class=\"form-control\" placeholder=\"Instagram\" aria-label=\"Username\" aria-describedby=\"basic-addon1\" name=\"intagram\">\r\n");
      out.write("												</div>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              					<div class=\"row clearfix\">\r\n");
      out.write("	              						<div class=\"col-lg-5\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<div class=\"input-group mb-3\">\r\n");
      out.write("	              									<input type=\"submit\" value=\"submit\" class=\"btn btn-success\">\r\n");
      out.write("	              								</div>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              						<div class=\"col-lg-5\">\r\n");
      out.write("	              							<div class=\"from-group\">\r\n");
      out.write("	              								<div class=\"input-group mb-3\">\r\n");
      out.write("	              									<input type=\"reset\" value=\"Cancel\" class=\"btn btn-black\">\r\n");
      out.write("	              								</div>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              						</div>\r\n");
      out.write("	              					</div>\r\n");
      out.write("              						</div>\r\n");
      out.write("              					</div>\r\n");
      out.write("              				</div>\r\n");
      out.write("              			</div>\r\n");
      out.write("              		</div>			\r\n");
      out.write("              					</form>\r\n");
      out.write("              				</div>\r\n");
      out.write("              			</div>\r\n");
      out.write("              		</div>\r\n");
      out.write("              	</div> \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>        \r\n");
      out.write("                \r\n");
      out.write("         <!-- Javascript -->\r\n");
      out.write("    <script src=\"assets/bundles/libscripts.bundle.js\"></script>\r\n");
      out.write("    <script src=\"assets/bundles/vendorscripts.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/bundles/chartist.bundle.js\"></script>\r\n");
      out.write("    <script src=\"assets/bundles/knob.bundle.js\"></script>\r\n");
      out.write("    <!-- Jquery Knob-->\r\n");
      out.write("    <script src=\"assets/bundles/flotscripts.bundle.js\"></script>\r\n");
      out.write("    <!-- flot charts Plugin Js -->\r\n");
      out.write("    <script src=\"../assets/vendor/toastr/toastr.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/flot-charts/jquery.flot.selection.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/bundles/mainscripts.bundle.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/index.js\"></script>       \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
